name: build

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/build.yml"
      - "assets/**"
      - "cmd/**"
      - "internal/**"
      - "scripts/**"
      - "main.go"
      - "go.mod"
      - "go.sum"

  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/build.yml"
      - "assets/**"
      - "cmd/**"
      - "internal/**"
      - "scripts/**"
      - "main.go"
      - "go.mod"
      - "go.sum"

  workflow_dispatch:

jobs:
  meta:
    uses: ./.github/workflows/meta.yml

  ubuntu:
    needs: meta
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    strategy:
      fail-fast: false

    steps:
      - name: Update System
        run: |
          pacman -Syu --noconfirm

      - name: Install Git
        run: |
          pacman -S --noconfirm git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        run: |
          go mod download

      - name: Download MaaFramework
        run: |
          go run ./scripts/download -token=${{ secrets.GITHUB_TOKEN }} --all

      - name: Build
        run: |
          go run ./scripts/build -version=${{ needs.meta.outputs.tag }} --all

      - name: Install
        run: |
         go run ./scripts/install --all

      - uses: actions/upload-artifact@v4
        with:
          name: eam-linux-amd64
          path: "install/linux-amd64"

      - uses: actions/upload-artifact@v4
        with:
          name: eam-linux-arm64
          path: "install/linux-arm64"

      - uses: actions/upload-artifact@v4
        with:
          name: eam-windows-amd64
          path: "install/windows-amd64"

      - uses: actions/upload-artifact@v4
        with:
          name: eam-windows-arm64
          path: "install/windows-arm64"

      - uses: actions/upload-artifact@v4
        with:
          name: eam-darwin-amd64
          path: "install/darwin-amd64"

      - uses: actions/upload-artifact@v4
        with:
          name: eam-darwin-arm64
          path: "install/darwin-arm64"
      